algo: "td3"
state_dim: 245
h_state_dim: 178
action_dim: 8
response_dim: 8
h_response_dim: 2
max_buffer_size: 3000000
discount: 0.9
tau: 0.001
policy_noise: 0.1
noise_clip: 0.2
policy_freq: 2
lr: 0.00005
alpha: 2.5

test_every: 1000
test_n_user: 500
test_immediate: True
log_every: 1000

n_epoch: 5
batch_size: 4096

save_model: True
use_tensorboard: True

pref_buffer_size: 20000
seg_length: 100
pretrain_n_epoch: 3
pref_batch_size: 256
fine_tune_reward: True
return_type: 0
true_reward: False
n_predictor: 1
n_vibpredictor: 0